### ISSUE TITLE
failed to compiled in the distributedlog_2.11-0.4.0-incubating

### ISSUE THREAD

**Issue by Li-Haihui** [apache/distributedlog#174] opened 2017-09-04 06:52 UTC
Is this a question, feature request, or bug report?

**QUESTION**

In the distributedlog_2.11-0.4.0-incubating compilation process: Error occurred
                                Failed to execute goal on project distributedlog-protocol_2.11: Could not resolve dependencies for project org.apache.distributedlog:distributedlog-protocol_2.11:jar:0.4.0-incubating: Failed to collect dependencies at org.apache.bookkeeper.stats:bookkeeper-stats-api:jar:4.3.7-TWTTR-OSS: Failed to read artifact descriptor for org.apache.bookkeeper.stats:bookkeeper-stats-api:jar:4.3.7-TWTTR-OSS: Could not transfer artifact org.apache.bookkeeper.stats:bookkeeper-stats-api:pom:4.3.7-TWTTR-OSS from/to central (http://repo.maven.apache.org/maven2/): repo.maven.apache.org:80 failed to respond -> [Help 1]

did you used Bookkeeper_4.3.7 ?
@sijie

**Comment by sijie** [comment] 2017-09-04 17:50
@Li-Haihui 

> did you use BookKeeper_4.3.7?

0.4.0-incubating is using twitter's folk of bookkeeper. so it is 4.3.7-TWTTR-OSS. We upgraded the bookkeeper dependency to depend on open source 4.5.0 at #135 . It will be released in 0.5.0, which will mostly come out this week.

> build failure

4.3.7-TWTTR-OSS is hosted at github. so the build process will fetch the dependency from github. what command did you run to build `distributedlog_2.11-0.4.0-incubating`? I tried on my laptop, it actually worked well.

**Comment by Li-Haihui** [comment] 2017-09-05 01:07
@sijie 

1. 0.5.0 question
now you update the DL at github, is it difference from your final version in 0.5.0?

2. build failure

i used this command to build distributedlog_2.11-0.4.0-incubating.
mvn clean
mvn install -DskipTests
mvn package -DskipTests
mvn clean install -Dmaven.test.skip=true

in the second step ,it is failed.

**Comment by sijie** [comment] 2017-09-05 01:16
@Li-Haihui 

> 0.5.0

4.5.0 will be the final bk version in 0.5.0.

**Comment by Li-Haihui** [comment] 2017-09-05 01:29
@sijie 
ok ,if i used this four commands to build 0.5.0, this is the same question in the jmh-0.4. so i remove jmh-0.4's compilation process. now it is passed.

**Comment by sijie** [comment] 2017-09-05 01:40
@Li-Haihui : 

Ah i see. It seems the problem is your cannot connect to github.com to fetch the bk 4.3.7 dependency. jmh-0.4 is used for backward compatibility testing, which it depends on `0.4.0-incubating`, and hence depends on bk 4.3.7 dependency.

Can you check your build environment to see if  you can connect to github.com?

**Comment by zhaijack** [comment] 2017-09-05 01:42
suspect this is a issue related to network or firewall in China, and caused some repository not reach-able,  but I have tried just now that without VPN it is also OK for "org.apache.bookkeeper.stats:bookkeeper-stats-api:pom:4.3.7-TWTTR-OSS".   Recently, seems github does not have a very stable connection in China, maybe that is the cause.

**Comment by Li-Haihui** [comment] 2017-09-05 02:00
@sijie 
is it affect to our development processes if i remove jmh-0.4?

**Comment by sijie** [comment] 2017-09-05 05:22
@Li-Haihui it doesn't. the existence of `jmh-0.4` is comparing performance between different versions.

**Comment by Li-Haihui** [comment] 2017-09-05 08:38
ok，now 0.5.0 is working.

**Comment by sijie** [comment] 2017-09-05 09:02
@Li-Haihui awesome!

**Closed** 2017-09-05 15:08 UTC
Labels: area/build, type/question
